server:
  port: 8889

spring:
  application:
    name: invitation-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:/postgresql://localhost:5442/invitation_management"
    username: root
    password: 123
  output:
    ansi:
      enabled: ALWAYS

info:
  component: Invitation Management Application
  version: 0.0.1

openapi:
  service:
    title: invitation-service doc
    version: 1.0.0
    url: http://localhost:8081
springdoc:
  api-docs:
    path: /invitation-service/v3/api-docs
  swagger-ui:
    path: /invitation-service/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

security:
  jwt:
    secret: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA