spring:
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibarnate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: "jdbc:/postgresql://localhost:5432/user_management"
    username: root
    password: 123